/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.util.Random;
import model.SessionManager;
import model.User;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Rao Hamza Tariq
 */
public class AnalysisCharts extends javax.swing.JFrame {

    /**
     * Creates new form AnalysisCharts
     */
    public AnalysisCharts() {
        initComponents();
        User user = SessionManager.getCurrentUser();
        SQL_MODEL db = new SQL_MODEL();
        UserData user_data = db.getUserData(user.getEmail());
        createRecurringChart(user_data.user_id);
        createIncomeVsExpenseChart(user_data.user_id);
        createTransactionFrequencyChart(user_data.user_id);
        createTopCategoriesChart(user_data.user_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void createIncomeVsExpenseChart(int user_id) {
    DefaultPieDataset dataset = new DefaultPieDataset();

    SQL_MODEL db = new SQL_MODEL();
    ResultSet rs;

    String query = "SELECT type, SUM(amount) as total_amount " +
                   "FROM transactions " +
                   "WHERE user_id = " +user_id+
                   " GROUP BY type";

    try {
        rs = db.SQL_Query(query);
        while (rs.next()) {
            String type = rs.getString("type");
            double totalAmount = rs.getDouble("total_amount");
            dataset.setValue(type, totalAmount);
        }
    } catch (Exception e) {
        System.out.println("Error: " + e);
    }

    JFreeChart chart = ChartFactory.createPieChart(
            "Income vs Expense",
            dataset,
            true,
            true,
            false
    );

    ChartPanel chartSwingPanel = new ChartPanel(chart);
    chartSwingPanel.setPreferredSize(new Dimension(500, 300));
    chartSwingPanel.setMaximumSize(new Dimension(500, 300));
    chartSwingPanel.setMinimumSize(new Dimension(500, 300));

    chart2.removeAll();
    chart2.setLayout(new BorderLayout());
    chart2.add(chartSwingPanel, BorderLayout.CENTER);
    chart2.revalidate();
    chart2.repaint();
}

    
    private void createRecurringChart(int user_id) {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    SQL_MODEL db = new SQL_MODEL();
    ResultSet rs;

    String query = "SELECT is_recurring, type, SUM(amount) AS total " +
                   "FROM transactions " +
                   "WHERE user_id = " + user_id +
                   " GROUP BY is_recurring, type";

    try {
        rs = db.SQL_Query(query);
        while (rs.next()) {
            int isRecurring = rs.getInt("is_recurring");
            String type = rs.getString("type");
            double total = rs.getDouble("total");

            String label = (isRecurring == 1) ? "Recurring" : "One-time";

            dataset.addValue(total, label, type); 
        }
    } catch (Exception e) {
        System.out.println("Error: " + e);
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Recurring vs One-Time Transactions",
            "Transaction Type",
            "Total Amount ($)",
            dataset
    );

    ChartPanel chartSwingPanel = new ChartPanel(chart);
    chartSwingPanel.setPreferredSize(new Dimension(500, 300));
    chartSwingPanel.setMaximumSize(new Dimension(500, 300));
    chartSwingPanel.setMinimumSize(new Dimension(500, 300));



    chart1.removeAll();
    chart1.setLayout(new BorderLayout());
    chart1.add(chartSwingPanel, BorderLayout.CENTER);
    chart1.revalidate();
    chart1.repaint();
}

    private void createTransactionFrequencyChart(int user_id) {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    SQL_MODEL db = new SQL_MODEL();
    ResultSet rs;

    String query = "SELECT MONTHNAME(date) AS month, COUNT(*) AS total " +
                   "FROM transactions " +
                   "WHERE user_id = " +user_id+
                   " GROUP BY MONTH(date) " +
                   "ORDER BY MONTH(date)";

    try {
        rs = db.SQL_Query(query);
        while (rs.next()) {
            String month = rs.getString("month");
            int count = rs.getInt("total");

            dataset.addValue(count, "Transactions", month);
        }
    } catch (Exception e) {
        System.out.println("Error: " + e);
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Transaction Frequency by Month",
            "Month",
            "Number of Transactions",
            dataset
    );

    ChartPanel chartSwingPanel = new ChartPanel(chart);
    chartSwingPanel.setPreferredSize(new Dimension(500, 300));
    chartSwingPanel.setMaximumSize(new Dimension(500, 300));
    chartSwingPanel.setMinimumSize(new Dimension(500, 300));

    chart3.removeAll();
    chart3.setLayout(new BorderLayout());
    chart3.add(chartSwingPanel, BorderLayout.CENTER);
    chart3.revalidate();
    chart3.repaint();
}

    
    private void createTopCategoriesChart(int user_id) {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    SQL_MODEL db = new SQL_MODEL();
    ResultSet rs;

    String query = "SELECT c.name AS category, SUM(t.amount) AS total " +
                   "FROM transactions t " +
                   "JOIN categories c ON t.category_id = c.id " +
                   "WHERE t.user_id = " +user_id+
                   "GROUP BY c.name " +
                   "ORDER BY total DESC " +
                   "LIMIT 5";

    try {
        rs = db.SQL_Query(query);
        while (rs.next()) {
            String category = rs.getString("category");
            double total = rs.getDouble("total");

            dataset.addValue(total, "Total Amount", category);
        }
    } catch (Exception e) {
        System.out.println("Error: " + e);
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Top 5 Categories by Total Amount",
            "Category",
            "Total Amount ($)",
            dataset,
            PlotOrientation.HORIZONTAL,  // <-- Makes it a horizontal bar chart
            false, true, false
    );

    ChartPanel chartSwingPanel = new ChartPanel(chart);
    chartSwingPanel.setPreferredSize(new Dimension(500, 300));
    chartSwingPanel.setMaximumSize(new Dimension(500, 300));
    chartSwingPanel.setMinimumSize(new Dimension(500, 300));

    chart4.removeAll();
    chart4.setLayout(new BorderLayout());
    chart4.add(chartSwingPanel, BorderLayout.CENTER);
    chart4.revalidate();
    chart4.repaint();
}

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        chart1 = new javax.swing.JPanel();
        chart2 = new javax.swing.JPanel();
        chart3 = new javax.swing.JPanel();
        chart4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        chart1.setBackground(new java.awt.Color(255, 255, 255));
        chart1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart1Layout = new javax.swing.GroupLayout(chart1);
        chart1.setLayout(chart1Layout);
        chart1Layout.setHorizontalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        chart1Layout.setVerticalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(chart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 270));

        chart2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart2Layout = new javax.swing.GroupLayout(chart2);
        chart2.setLayout(chart2Layout);
        chart2Layout.setHorizontalGroup(
            chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        chart2Layout.setVerticalGroup(
            chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(chart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 430, 270));

        chart3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart3Layout = new javax.swing.GroupLayout(chart3);
        chart3.setLayout(chart3Layout);
        chart3Layout.setHorizontalGroup(
            chart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        chart3Layout.setVerticalGroup(
            chart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(chart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, 270));

        chart4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chart4Layout = new javax.swing.GroupLayout(chart4);
        chart4.setLayout(chart4Layout);
        chart4Layout.setHorizontalGroup(
            chart4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        chart4Layout.setVerticalGroup(
            chart4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(chart4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalysisCharts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalysisCharts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalysisCharts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalysisCharts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalysisCharts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chart1;
    private javax.swing.JPanel chart2;
    private javax.swing.JPanel chart3;
    private javax.swing.JPanel chart4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
